os: Visual Studio 2017

init:
  - git config --global core.autocrlf input

build_script:
  - cmd: >-
      msbuild build.proj /t:restore /p:dev=14.0 &&
      msbuild build.proj /t:build /p:dev=14.0 &&
      msbuild build.proj /t:package /p:dev=14.0 /v:minimal

# we run the tests ourselves
test: off

deploy:
  - provider: NuGet
    api_key:
      secure: 7MS5+XWaFchMXFqzgneQCqo9U0DlxiPXe/KWWUnbCBDEizVn06EjdQZkWu1gbNOJ
    artifact: Package
    on:
      branch: /master|v2/

nuget:
  project_feed: true

artifacts:
  - path: out\*.nupkg
    name: Package
