os: Visual Studio 2015

init:
  - git config --global core.autocrlf input

build_script:
  - cmd: >-
      build.cmd
      
      cmd /C ".nuget\packages\coveralls.io\tools\coveralls.net.exe --opencover out\coverage.xml" && exit 0

# we run the tests ourselves in build.cmd for coverage
test: off

environment:
  COVERALLS_REPO_TOKEN:
    secure: l3O4lbgUscsMKm9M580fsx0rBDal/nTrtRTt3ZE6897ps9Q3USzEIwR254Z4CfKv

deploy:
  - provider: NuGet
    api_key:
      secure: 7MS5+XWaFchMXFqzgneQCqo9U0DlxiPXe/KWWUnbCBDEizVn06EjdQZkWu1gbNOJ
    artifact: Package
    on:
      branch: master

nuget:
  project_feed: true
  disable_publish_on_pr: true
  
artifacts:
  - path: out\*.nupkg
    name: Package