os: Visual Studio 2015

init:
  - git config --global core.autocrlf input

build_script:
  - build.cmd

# we run the tests ourselves in build.cmd
test: off

deploy:
  - provider: NuGet
    api_key:
      secure: 7MS5+XWaFchMXFqzgneQCqo9U0DlxiPXe/KWWUnbCBDEizVn06EjdQZkWu1gbNOJ
    artifact: Package
    on:
      branch: /master|v2/

nuget:
  project_feed: true

artifacts:
  - path: out\*.nupkg
    name: Package